version: 1
update_configs:
  - package_manager: javascript
    directory: '/'
    update_schedule: 'live'
    default_assignees:
      - 'JonnyBurger'
    automerged_updates:
      - match:
          dependency_type: 'all'
          update_type: 'all'
          dependency_name: '@types/*'
    version_requirement_updates: increase_versions
