on:
  push:
    branches:
      - master
name: Install and Test
jobs:
  install:
    name: Test
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@master
      - name: Install
        uses: 4Catalyzer/action-yarn@master
        with:
          args: install
      - name: Publish
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
          npm publish --access=public
        
