on: push
name: Install and Test
jobs:
  install:
    name: Test
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      INCREMENT_BUILD_ID: ${{ secrets.INCREMENT_BUILD_ID }}
    steps:
      - uses: actions/checkout@master
      - name: Test
        uses: actions/npm@59b64a598378f31e49cb76f27d6f3312b582f680
        with:
          args: i
      - name: Cache
        uses: actions/cache@v1.0.0
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install
        run: |
          npm install
      - name: Publish
        if: startsWith(github.ref, 'master')
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
          node -e "a=require('./package.json');a.version='2.1.$(curl https://increment.build/$INCREMENT_BUILD_ID)';require('fs').writeFileSync('package.json', JSON.stringify(a, null, 2))"
          npm publish --access=public
        
