on: push
name: Install and Test
jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@master
      - name: Install
        uses: actions/npm@59b64a598378f31e49cb76f27d6f3312b582f680
        with:
          args: install
      - name: Test
        uses: actions/npm@59b64a598378f31e49cb76f27d6f3312b582f680
        with:
          args: test
      - name: Publish
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
          npm publish --access=public
